-- Phase 1: Snowflake sandbox database and schema setup.
-- Run after 00_setup_roles_warehouse.sql.
-- Recommended execution role: SYSADMIN.

USE ROLE SYSADMIN;
USE WAREHOUSE HC_GOV_WH;

CREATE DATABASE IF NOT EXISTS HC_GOV_DEMO
  COMMENT = 'Healthcare Data Governance Demo sandbox database.';

CREATE SCHEMA IF NOT EXISTS HC_GOV_DEMO.BRONZE
  COMMENT = 'Raw ingestion layer for source-system data.';

CREATE SCHEMA IF NOT EXISTS HC_GOV_DEMO.SILVER
  COMMENT = 'Standardized and cleansed healthcare data layer.';

CREATE SCHEMA IF NOT EXISTS HC_GOV_DEMO.GOLD
  COMMENT = 'Business-ready dimensional and fact models.';

CREATE SCHEMA IF NOT EXISTS HC_GOV_DEMO.GOVERNANCE
  COMMENT = 'Governance metadata, classifications, audit results, alerts, and steward assignments.';

CREATE SCHEMA IF NOT EXISTS HC_GOV_DEMO.ANALYTICS
  COMMENT = 'Dashboard-facing views and KPI outputs.';

GRANT USAGE ON DATABASE HC_GOV_DEMO TO ROLE HC_DEMO_ADMIN;
GRANT USAGE ON DATABASE HC_GOV_DEMO TO ROLE HC_PHYSICIAN_ROLE;
GRANT USAGE ON DATABASE HC_GOV_DEMO TO ROLE HC_ANALYST_ROLE;
GRANT USAGE ON DATABASE HC_GOV_DEMO TO ROLE HC_STEWARD_ROLE;

GRANT ALL PRIVILEGES ON SCHEMA HC_GOV_DEMO.BRONZE TO ROLE HC_DEMO_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA HC_GOV_DEMO.SILVER TO ROLE HC_DEMO_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA HC_GOV_DEMO.GOLD TO ROLE HC_DEMO_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA HC_GOV_DEMO.GOVERNANCE TO ROLE HC_DEMO_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA HC_GOV_DEMO.ANALYTICS TO ROLE HC_DEMO_ADMIN;

GRANT USAGE ON SCHEMA HC_GOV_DEMO.BRONZE TO ROLE HC_STEWARD_ROLE;
GRANT USAGE ON SCHEMA HC_GOV_DEMO.SILVER TO ROLE HC_PHYSICIAN_ROLE;
GRANT USAGE ON SCHEMA HC_GOV_DEMO.SILVER TO ROLE HC_ANALYST_ROLE;
GRANT USAGE ON SCHEMA HC_GOV_DEMO.SILVER TO ROLE HC_STEWARD_ROLE;
GRANT USAGE ON SCHEMA HC_GOV_DEMO.GOLD TO ROLE HC_PHYSICIAN_ROLE;
GRANT USAGE ON SCHEMA HC_GOV_DEMO.GOLD TO ROLE HC_ANALYST_ROLE;
GRANT USAGE ON SCHEMA HC_GOV_DEMO.GOLD TO ROLE HC_STEWARD_ROLE;
GRANT USAGE ON SCHEMA HC_GOV_DEMO.GOVERNANCE TO ROLE HC_STEWARD_ROLE;
GRANT USAGE ON SCHEMA HC_GOV_DEMO.ANALYTICS TO ROLE HC_PHYSICIAN_ROLE;
GRANT USAGE ON SCHEMA HC_GOV_DEMO.ANALYTICS TO ROLE HC_ANALYST_ROLE;
GRANT USAGE ON SCHEMA HC_GOV_DEMO.ANALYTICS TO ROLE HC_STEWARD_ROLE;

-- Future object grants make later phases easier to run without revisiting Phase 1.
GRANT SELECT ON FUTURE TABLES IN SCHEMA HC_GOV_DEMO.SILVER TO ROLE HC_PHYSICIAN_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HC_GOV_DEMO.SILVER TO ROLE HC_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HC_GOV_DEMO.SILVER TO ROLE HC_STEWARD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HC_GOV_DEMO.GOLD TO ROLE HC_PHYSICIAN_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HC_GOV_DEMO.GOLD TO ROLE HC_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HC_GOV_DEMO.GOLD TO ROLE HC_STEWARD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HC_GOV_DEMO.GOVERNANCE TO ROLE HC_STEWARD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HC_GOV_DEMO.ANALYTICS TO ROLE HC_PHYSICIAN_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HC_GOV_DEMO.ANALYTICS TO ROLE HC_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HC_GOV_DEMO.ANALYTICS TO ROLE HC_STEWARD_ROLE;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA HC_GOV_DEMO.SILVER TO ROLE HC_PHYSICIAN_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA HC_GOV_DEMO.SILVER TO ROLE HC_ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA HC_GOV_DEMO.SILVER TO ROLE HC_STEWARD_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA HC_GOV_DEMO.GOLD TO ROLE HC_PHYSICIAN_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA HC_GOV_DEMO.GOLD TO ROLE HC_ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA HC_GOV_DEMO.GOLD TO ROLE HC_STEWARD_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA HC_GOV_DEMO.GOVERNANCE TO ROLE HC_STEWARD_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA HC_GOV_DEMO.ANALYTICS TO ROLE HC_PHYSICIAN_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA HC_GOV_DEMO.ANALYTICS TO ROLE HC_ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA HC_GOV_DEMO.ANALYTICS TO ROLE HC_STEWARD_ROLE;

-- Grants for dynamic tables (current and future) to analyst/physician/steward roles
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA HC_GOV_DEMO.SILVER TO ROLE HC_PHYSICIAN_ROLE;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA HC_GOV_DEMO.SILVER TO ROLE HC_ANALYST_ROLE;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA HC_GOV_DEMO.SILVER TO ROLE HC_STEWARD_ROLE;

GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA HC_GOV_DEMO.SILVER TO ROLE HC_PHYSICIAN_ROLE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA HC_GOV_DEMO.SILVER TO ROLE HC_ANALYST_ROLE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA HC_GOV_DEMO.SILVER TO ROLE HC_STEWARD_ROLE;

GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA HC_GOV_DEMO.GOLD TO ROLE HC_PHYSICIAN_ROLE;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA HC_GOV_DEMO.GOLD TO ROLE HC_ANALYST_ROLE;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA HC_GOV_DEMO.GOLD TO ROLE HC_STEWARD_ROLE;

GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA HC_GOV_DEMO.GOLD TO ROLE HC_PHYSICIAN_ROLE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA HC_GOV_DEMO.GOLD TO ROLE HC_ANALYST_ROLE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA HC_GOV_DEMO.GOLD TO ROLE HC_STEWARD_ROLE;

GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA HC_GOV_DEMO.ANALYTICS TO ROLE HC_PHYSICIAN_ROLE;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA HC_GOV_DEMO.ANALYTICS TO ROLE HC_ANALYST_ROLE;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA HC_GOV_DEMO.ANALYTICS TO ROLE HC_STEWARD_ROLE;

GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA HC_GOV_DEMO.ANALYTICS TO ROLE HC_PHYSICIAN_ROLE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA HC_GOV_DEMO.ANALYTICS TO ROLE HC_ANALYST_ROLE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA HC_GOV_DEMO.ANALYTICS TO ROLE HC_STEWARD_ROLE;

-- Governance schema: stewards only
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA HC_GOV_DEMO.GOVERNANCE TO ROLE HC_STEWARD_ROLE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA HC_GOV_DEMO.GOVERNANCE TO ROLE HC_STEWARD_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA HC_GOV_DEMO.BRONZE TO ROLE OVALEDGE_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HC_GOV_DEMO.BRONZE TO ROLE OVALEDGE_ROLE;
GRANT READ ON STAGE HC_GOV_DEMO.BRONZE.RAW_DATA_STAGE TO ROLE OVALEDGE_ROLE;
GRANT USAGE ON SCHEMA HC_GOV_DEMO.BRONZE TO ROLE OVALEDGE_ROLE;