-- Phase 2: Load staged synthetic CSV data into Bronze tables.
-- Run after uploading files to @HC_GOV_DEMO.BRONZE.RAW_DATA_STAGE.
-- See docs/phase_2_bronze_setup.md for Snowflake CLI upload commands.

USE ROLE SYSADMIN;
USE WAREHOUSE HC_GOV_WH;
USE DATABASE HC_GOV_DEMO;
USE SCHEMA BRONZE;

TRUNCATE TABLE BRZ_PATIENT_MASTER;
TRUNCATE TABLE BRZ_PATIENT_ENCOUNTER;
TRUNCATE TABLE BRZ_LAB_RESULTS;
TRUNCATE TABLE BRZ_PHARMACY_ORDERS;
TRUNCATE TABLE BRZ_CLAIMS;

COPY INTO BRZ_PATIENT_MASTER
FROM @RAW_DATA_STAGE/patient_master.csv
FILE_FORMAT = (FORMAT_NAME = BRONZE_CSV_FORMAT)
ON_ERROR = ABORT_STATEMENT;

COPY INTO BRZ_PATIENT_ENCOUNTER
FROM @RAW_DATA_STAGE/patient_encounter.csv
FILE_FORMAT = (FORMAT_NAME = BRONZE_CSV_FORMAT)
ON_ERROR = ABORT_STATEMENT;

COPY INTO BRZ_LAB_RESULTS
FROM @RAW_DATA_STAGE/lab_results.csv
FILE_FORMAT = (FORMAT_NAME = BRONZE_CSV_FORMAT)
ON_ERROR = ABORT_STATEMENT;

COPY INTO BRZ_PHARMACY_ORDERS
FROM @RAW_DATA_STAGE/pharmacy_orders.csv
FILE_FORMAT = (FORMAT_NAME = BRONZE_CSV_FORMAT)
ON_ERROR = ABORT_STATEMENT;

COPY INTO BRZ_CLAIMS
FROM @RAW_DATA_STAGE/claims.csv
FILE_FORMAT = (FORMAT_NAME = BRONZE_CSV_FORMAT)
ON_ERROR = ABORT_STATEMENT;

