-- Phase 2: Load staged synthetic CSV data into Bronze tables from the 1000-row test dataset.
-- Run after uploading files to @HC_GOV_DEMO.BRONZE.RAW_DATA_STAGE.
-- See docs/phase_2_bronze_setup.md for Snowflake CLI upload commands.

USE ROLE SYSADMIN;
USE WAREHOUSE HC_GOV_WH;
USE DATABASE HC_GOV_DEMO;
USE SCHEMA BRONZE;

TRUNCATE TABLE BRZ_PATIENT_MASTER;
TRUNCATE TABLE BRZ_PATIENT_ENCOUNTER;
TRUNCATE TABLE BRZ_LAB_RESULTS;
TRUNCATE TABLE BRZ_PHARMACY_ORDERS;
TRUNCATE TABLE BRZ_CLAIMS;
TRUNCATE TABLE BRZ_APPOINTMENT;
TRUNCATE TABLE BRZ_PROVIDER_MASTER;

COPY INTO BRZ_PATIENT_MASTER
FROM @RAW_DATA_STAGE/patient_master_1000.csv
FILE_FORMAT = (FORMAT_NAME = BRONZE_CSV_FORMAT)
ON_ERROR = ABORT_STATEMENT;

COPY INTO BRZ_PATIENT_ENCOUNTER
FROM @RAW_DATA_STAGE/patient_encounter_1000.csv
FILE_FORMAT = (FORMAT_NAME = BRONZE_CSV_FORMAT)
ON_ERROR = ABORT_STATEMENT;

COPY INTO BRZ_LAB_RESULTS
FROM @RAW_DATA_STAGE/lab_results_1000.csv
FILE_FORMAT = (FORMAT_NAME = BRONZE_CSV_FORMAT)
ON_ERROR = ABORT_STATEMENT;

COPY INTO BRZ_PHARMACY_ORDERS
FROM @RAW_DATA_STAGE/pharmacy_orders_1000.csv
FILE_FORMAT = (FORMAT_NAME = BRONZE_CSV_FORMAT)
ON_ERROR = ABORT_STATEMENT;

COPY INTO BRZ_CLAIMS
FROM @RAW_DATA_STAGE/claims_1000.csv
FILE_FORMAT = (FORMAT_NAME = BRONZE_CSV_FORMAT)
ON_ERROR = ABORT_STATEMENT;

COPY INTO BRZ_APPOINTMENT
FROM @RAW_DATA_STAGE/appointments_1000.csv
FILE_FORMAT = (FORMAT_NAME = BRONZE_CSV_FORMAT)
ON_ERROR = ABORT_STATEMENT;

COPY INTO BRZ_PROVIDER_MASTER
FROM @RAW_DATA_STAGE/provider_master_1000.csv
FILE_FORMAT = (FORMAT_NAME = BRONZE_CSV_FORMAT)
ON_ERROR = ABORT_STATEMENT;
