-- =============================================================================
-- Create user OVALEDGE and grant HC_ANALYST_ROLE for SELECT access
-- to HC_GOV_DEMO database
-- =============================================================================

USE ROLE SECURITYADMIN;
-- Step 1: Create the user
CREATE USER IF NOT EXISTS OVALEDGE
    PASSWORD = 'md2026OVL@0606'
    DEFAULT_ROLE = 'OVALEDGE_ROLE'
    MUST_CHANGE_PASSWORD = FALSE;

-- Step 2: Create a dedicated role for OVALEDGE
CREATE ROLE IF NOT EXISTS OVALEDGE_ROLE;

-- Step 3: Grant the role to the user
GRANT ROLE OVALEDGE_ROLE TO USER OVALEDGE;

-- Step 4: Grant HC_ANALYST_ROLE to OVALEDGE_ROLE (inherits all SELECT privileges)
GRANT ROLE HC_ANALYST_ROLE TO ROLE OVALEDGE_ROLE;

-- Step 5: Create GOVERNANCE_WH warehouse using SYSADMIN
USE ROLE SYSADMIN;
CREATE WAREHOUSE IF NOT EXISTS GOVERNANCE_WH;

-- Step 6: Grant USAGE on GOVERNANCE_WH to OVALEDGE_ROLE
USE ROLE ACCOUNTADMIN;
GRANT USAGE ON WAREHOUSE GOVERNANCE_WH TO ROLE OVALEDGE_ROLE;

-- Step 7: Create GOVERNANCE database with TAGS and POLICIES schemas
USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS GOVERNANCE;
CREATE SCHEMA IF NOT EXISTS GOVERNANCE.TAGS;
CREATE SCHEMA IF NOT EXISTS GOVERNANCE.POLICIES;

-- Step 8: Create TAG_ADMIN and MASKING_ADMIN roles using SECURITYADMIN
USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS TAG_ADMIN;
CREATE ROLE IF NOT EXISTS MASKING_ADMIN;

-- Step 9: Grant privileges to TAG_ADMIN and MASKING_ADMIN
GRANT USAGE ON DATABASE GOVERNANCE TO ROLE TAG_ADMIN;
GRANT USAGE ON SCHEMA GOVERNANCE.TAGS TO ROLE TAG_ADMIN;
GRANT CREATE TAG ON SCHEMA GOVERNANCE.TAGS TO ROLE TAG_ADMIN;
GRANT APPLY TAG ON ACCOUNT TO ROLE TAG_ADMIN;

GRANT USAGE ON DATABASE GOVERNANCE TO ROLE MASKING_ADMIN;
GRANT USAGE ON SCHEMA GOVERNANCE.POLICIES TO ROLE MASKING_ADMIN;
GRANT CREATE MASKING POLICY ON SCHEMA GOVERNANCE.POLICIES TO ROLE MASKING_ADMIN;
GRANT APPLY MASKING POLICY ON ACCOUNT TO ROLE MASKING_ADMIN;

-- Step 10: Assign TAG_ADMIN and MASKING_ADMIN to OVALEDGE_ROLE
GRANT ROLE TAG_ADMIN TO ROLE OVALEDGE_ROLE;
GRANT ROLE MASKING_ADMIN TO ROLE OVALEDGE_ROLE;
