-- Phase 2 validation queries.
-- These queries confirm Bronze row counts, visible raw PHI, and injected DQ failures.

USE ROLE SYSADMIN;
USE WAREHOUSE HC_GOV_WH;
USE DATABASE HC_GOV_DEMO;

SELECT 'BRZ_PATIENT_MASTER' AS table_name, COUNT(*) AS row_count FROM BRONZE.BRZ_PATIENT_MASTER
UNION ALL
SELECT 'BRZ_PATIENT_ENCOUNTER', COUNT(*) FROM BRONZE.BRZ_PATIENT_ENCOUNTER
UNION ALL
SELECT 'BRZ_LAB_RESULTS', COUNT(*) FROM BRONZE.BRZ_LAB_RESULTS
UNION ALL
SELECT 'BRZ_PHARMACY_ORDERS', COUNT(*) FROM BRONZE.BRZ_PHARMACY_ORDERS
UNION ALL
SELECT 'BRZ_CLAIMS', COUNT(*) FROM BRONZE.BRZ_CLAIMS
ORDER BY table_name;

SELECT
  patient_id,
  medical_record_number,
  patient_first_name,
  patient_last_name,
  dob,
  ssn,
  phone_number,
  address_line1
FROM BRONZE.BRZ_PATIENT_MASTER
ORDER BY ingestion_timestamp
LIMIT 5;

SELECT 'NULL_PATIENT_ID' AS check_name, COUNT(*) AS failed_records
FROM BRONZE.BRZ_PATIENT_MASTER
WHERE patient_id IS NULL
UNION ALL
SELECT 'FUTURE_DOB', COUNT(*)
FROM BRONZE.BRZ_PATIENT_MASTER
WHERE dob > CURRENT_DATE()
UNION ALL
SELECT 'DISCHARGE_BEFORE_ADMISSION', COUNT(*)
FROM BRONZE.BRZ_PATIENT_ENCOUNTER
WHERE discharge_date < admission_date
UNION ALL
SELECT 'OUT_OF_RANGE_BLOOD_GLUCOSE', COUNT(*)
FROM BRONZE.BRZ_LAB_RESULTS
WHERE test_code = 'GLU'
  AND result_value NOT BETWEEN 40 AND 600
UNION ALL
SELECT 'NULL_LAB_RESULT_VALUE', COUNT(*)
FROM BRONZE.BRZ_LAB_RESULTS
WHERE result_value IS NULL
ORDER BY check_name;

